function init(self)
	self.spawned = false
end

function on_message(self, message_id, message)
	if self.spawned then
		return
	end

	if message_id == hash('trigger_response') then
		self.spawned = true
		print("spawn boss")
		local pos = go.get_position("/spawnpoint")
		print(pos)
		local created_ids = collectionfactory.create("#spawn", pos, vmath.euler_to_quat(0, 0, 0), {}, vmath.vector3(4, 4, 1))
		print(created_ids)
	end
end