-- go.property("prefix_number", 1)
-- go.property("count", 0)

-- local function unsummon()
--     go.get(url, property)
-- end

-- function init(self)
--     self.prefix_number = math.floor(self.prefix_number)
--     self.count = math.floor(self.count)
-- end

-- function on_message(self, message_id, message, sender)
--     if (message_id == hash('trigger_response')) then
--         for i = 1, self.count, 1 do
--             unsummon(i)
--         end
--     end
-- end
